### ISSUE TITLE
Login sometimes doesn't work without several refreshes

### ISSUE THREAD

**Issue by necrobuffalo** [capstoneteamb/capstone360#87] opened 2019-05-22 02:17 UTC

**Comment by J8cob1** [comment] 2019-06-05 04:48
Being fixed in the refactor branch (I think)

**Comment by pdx-cs-lbryan** [comment] 2019-06-08 04:44
Can this one be closed?

**Comment by J8cob1** [comment] 2019-06-08 07:39
This one is interesting because the cause might have been bad db queries blocking up the db. If those are gone, we probably can. If not, we might still be able to because we might fix the problems or file new issues anyway?

**Comment by pdx-cs-lbryan** [comment] 2019-06-09 05:01
tonight or tomorrow I'll be implement session rollbacks across exceptions. based on some testing, that seems to be the cause of this

**Comment by pdx-cs-lbryan** [comment] 2019-06-10 05:23
Marked this as close given that I believe the rollback addition and bug fixes have addressed this

**Closed as completed** 2019-06-10 05:23 UTC
